# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/SoundBaordQtwd7072.ui',
# licensing of '/tmp/SoundBaordQtwd7072.ui' applies.
#
# Created: Wed Oct  2 10:27:09 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SoundBoardQt(object):
    def setupUi(self, SoundBoardQt):
        SoundBoardQt.setObjectName("SoundBoardQt")
        SoundBoardQt.resize(783, 641)
        SoundBoardQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SoundBoardQt)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.silencieux = QtWidgets.QPushButton(SoundBoardQt)
        self.silencieux.setObjectName("silencieux")
        self.verticalLayout.addWidget(self.silencieux)
        self.pushButton_8 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_2 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_7 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_3 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_9 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.pushButton_6 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_15 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_10 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_17 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_12 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(SoundBoardQt)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_2.addWidget(self.pushButton_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(SoundBoardQt)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.Volume = QtWidgets.QDial(SoundBoardQt)
        self.Volume.setObjectName("Volume")
        self.verticalLayout_3.addWidget(self.Volume)
        self.pushButton = QtWidgets.QPushButton(SoundBoardQt)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(SoundBoardQt)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(SoundBoardQt)
        QtCore.QMetaObject.connectSlotsByName(SoundBoardQt)

    def retranslateUi(self, SoundBoardQt):
        SoundBoardQt.setWindowTitle(QtWidgets.QApplication.translate("SoundBoardQt", "SoundBoardQt", None, -1))
        self.silencieux.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Silencieux", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Batterie", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Dong", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Cris", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Hurlement", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Sonnerie", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Singe", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Pinson", None, -1))
        self.pushButton_11.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Darth Vador", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("SoundBoardQt", "R2D2", None, -1))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Cloche", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Feux d\'artifesse", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Xylophone", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Pinpon", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("SoundBoardQt", "flute (la chevre)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Volume", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("SoundBoardQt", "STOP", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("SoundBoardQt", "Ajouter", None, -1))

